import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind
df = pd.read_csv("/content/archive (4).zip")
print("FIRST FIVE ROWS")
print(df.head())
print("\nDATASET INFORMATION")
df.info()
print("\nDATASET SIZE")
print(df.shape)
print("\nCOLUMN NAMES")
print(df.columns)
print("\nMISSING VALUES")
print(df.isnull().sum())
print("\nDESCRIPTIVE STATISTICS")
print(df.describe())
print("\nMEAN")
print(df[["math score", "reading score", "writing score"]].mean())
print("\nMEDIAN")
print(df[["math score", "reading score", "writing score"]].median())
print("\nSTANDARD DEVIATION")
print(df[["math score", "reading score", "writing score"]].std())
print("\nMINIMUM")
print(df[["math score", "reading score", "writing score"]].min())
print("\nMAXIMUM")
print(df[["math score", "reading score", "writing score"]].max())
plt.figure()
plt.hist(df["math score"], bins=10)
plt.xlabel("Math Score")
plt.ylabel("Number of Students")
plt.title("Distribution of Math Scores")
plt.show()
plt.figure()
plt.hist(df["reading score"], bins=10)
plt.xlabel("Reading Score")
plt.ylabel("Number of Students")
plt.title("Distribution of Reading Scores")
plt.show()
plt.figure()
plt.hist(df["writing score"], bins=10)
plt.xlabel("Writing Score")
plt.ylabel("Number of Students")
plt.title("Distribution of Writing Scores")
plt.show()
plt.figure()
df[["math score", "reading score", "writing score"]].boxplot()
plt.title("Boxplot of Student Scores")
plt.ylabel("Score")
plt.show()
plt.figure()
plt.scatter(df["math score"], df["reading score"])
plt.xlabel("Math Score")
plt.ylabel("Reading Score")
plt.title("Math Score vs Reading Score")
plt.show()
plt.figure()
plt.scatter(df["math score"], df["writing score"])
plt.xlabel("Math Score")
plt.ylabel("Writing Score")
plt.title("Math Score vs Writing Score")
plt.show()
plt.figure()
plt.scatter(df["reading score"], df["writing score"])
plt.xlabel("Reading Score")
plt.ylabel("Writing Score")
plt.title("Reading Score vs Writing Score")
plt.show()
print("\nCORRELATION MATRIX")
correlation = df[
    ["math score", "reading score", "writing score"]
].corr()
print(correlation)
plt.figure()
plt.imshow(correlation, cmap="coolwarm")
plt.colorbar()
plt.xticks(
    range(len(correlation.columns)),
    correlation.columns,
    rotation=45
)
plt.yticks(
    range(len(correlation.columns)),
    correlation.columns
    )
plt.title("Correlation Matrix")
plt.show()
print("\nCOVARIANCE MATRIX")
covariance = df[
    ["math score", "reading score", "writing score"]
].cov()
print(covariance)
print("\nAVERAGE SCORES")
average_scores = df[
    ["math score", "reading score", "writing score"]
].mean()
print(average_scores)
plt.figure()
average_scores.plot(kind="bar")
plt.xlabel("Subjects")
plt.ylabel("Average Score")
plt.title("Average Score by Subject")
plt.show()
print("\nGENDER-WISE AVERAGE SCORES")
gender_scores = df.groupby("gender")[
    ["math score", "reading score", "writing score"]
].mean()
print(gender_scores)
gender_scores.plot(kind="bar")
plt.xlabel("Gender")
plt.ylabel("Average Score")
plt.title("Gender-wise Average Scores")
plt.xticks(rotation=0)
plt.show()
print("\nTEST PREPARATION COURSE ANALYSIS")
preparation_scores = df.groupby("test preparation course")[
    ["math score", "reading score", "writing score"]
].mean()
print(preparation_scores)
preparation_scores.plot(kind="bar")
plt.xlabel("Test Preparation Course")
plt.ylabel("Average Score")
plt.title("Test Preparation vs Student Scores")
plt.xticks(rotation=0)
plt.show()
completed = df[
    df["test preparation course"] == "completed"
]["math score"]
none = df[
    df["test preparation course"] == "none"
]["math score"]
t_stat, p_value = ttest_ind(completed, none)
print("\nHYPOTHESIS TESTING")
print("T-statistic:", t_stat)
print("P-value:", p_value)
if p_value < 0.05:
    print("Result: Reject the null hypothesis.")
    print("There is a significant difference in math scores.")
else:
    print("Result: Accept the null hypothesis.")
    print("There is no significant difference in math scores.")
print("\nCONCLUSION")
print("1. Descriptive statistics show the average performance of students.")
print("2. Histograms show the distribution of math, reading and writing scores.")
print("3. Boxplots help identify the spread and possible outliers.")
print("4. Correlation shows the relationship between different subject scores.")
print("5. Covariance shows how two variables change together.")
print("6. Bivariate analysis compares two variables.")
print("7. Multivariate analysis compares multiple subject scores.")
print("8. Hypothesis testing checks whether test preparation has a significant effect on math scores.")
